### ISSUE TITLE
is it good to add candle decompiler  in dexter ?

### ISSUE THREAD

**Issue by PranavPurwar** [MikeAndrson/Dexter#2]
Do you think, it will be a good idea to add candle decompiler in dexter  ?

**Comment by omeraydindev** [comment]
If you're talking about https://github.com/bradsdavis/candle-decompiler, the author writes and I quote: 

`"it is far from complete."` and `"Currently, the state of the decompiler is that it only decompiles a subset of the JVM operations; if you are looking for a decompiler, please check out the many closed options at this point.  Candle Decompiler has a long way to go to catch up with these fine tools, and this is more of a testing ground than anything at this point."`

on its README. I don't think it's a good idea to add a decompiler that _"only decompiles a subset of the JVM operations"_.

**Comment by PranavPurwar** [comment]
ok sir

**Comment by PranavPurwar** [comment]
btw sir, this may help you to add krakatau disassembler, it's using Jython
https://github.com/alexkasko/krakatau-java

**Comment by PranavPurwar** [comment]
Another link that may help in future
https://github.com/apache/commons-bcel
